-- =============================================================================
-- PROJECT: End-to-End E-Commerce Platform 
-- AUTHOR:  ABHISHEK GHOSAL
-- PURPOSE: Demonstrates 1NF, 2NF, 3NF, BCNF Normalization & ACID Compliance
-- =============================================================================

-- Uncomment the following lines to DROP existing tables (RESET DATABASE)
-- DROP TABLE audit_logs CASCADE CONSTRAINTS PURGE;
-- DROP TABLE returns CASCADE CONSTRAINTS PURGE;
-- DROP TABLE shipments CASCADE CONSTRAINTS PURGE;
-- DROP TABLE payments CASCADE CONSTRAINTS PURGE;
-- DROP TABLE order_items CASCADE CONSTRAINTS PURGE;
-- DROP TABLE orders CASCADE CONSTRAINTS PURGE;
-- DROP TABLE cart_items CASCADE CONSTRAINTS PURGE;
-- DROP TABLE shopping_cart CASCADE CONSTRAINTS PURGE;
-- DROP TABLE promotions CASCADE CONSTRAINTS PURGE;
-- DROP TABLE product_inventory CASCADE CONSTRAINTS PURGE;
-- DROP TABLE products CASCADE CONSTRAINTS PURGE;
-- DROP TABLE category_managers CASCADE CONSTRAINTS PURGE;
-- DROP TABLE categories CASCADE CONSTRAINTS PURGE;
-- DROP TABLE customer_addresses CASCADE CONSTRAINTS PURGE;
-- DROP TABLE customers CASCADE CONSTRAINTS PURGE;
-- PURGE RECYCLEBIN;
-- =============================================================================

-- =============================================================================
-- 1. CUSTOMERS (Base table for 3NF demonstration)
--    Note: No transitive dependencies (e.g., City/State are moved to addresses).
-- =============================================================================
CREATE TABLE customers (
    customer_id      NUMBER(10) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name        VARCHAR2(100) NOT NULL,
    email            VARCHAR2(100) NOT NULL UNIQUE,
    hashed_password  VARCHAR2(255) NOT NULL,  -- Stores SHA-256 hash
    phone            VARCHAR2(20),
    created_date     DATE DEFAULT SYSDATE,
    is_active        CHAR(1) DEFAULT 'Y' CONSTRAINT chk_cust_active CHECK (is_active IN ('Y', 'N'))
);

COMMENT ON TABLE customers IS '3NF: Removed City/State/Country to avoid transitive dependency on Order_ID.';
COMMENT ON COLUMN customers.email IS 'Unique constraint ensures no duplicate users.';
COMMENT ON COLUMN customers.hashed_password IS 'Stores SHA-256 hashed password for security.';

-- =============================================================================
-- 2. CATEGORIES (Supports hierarchical data and BCNF)
--    Self-referencing FK for parent-child categories.
-- =============================================================================
CREATE TABLE categories (
    category_id        NUMBER(10) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_name      VARCHAR2(100) NOT NULL,
    parent_category_id NUMBER(10) CONSTRAINT fk_cat_parent REFERENCES categories(category_id)
);

COMMENT ON TABLE categories IS 'Supports BCNF via the CATEGORY_MANAGERS table split.';

-- =============================================================================
-- 3. CUSTOMER_ADDRESSES (3NF Implementation)
--    We store multiple addresses per user. ORDERS reference this table.
-- =============================================================================
CREATE TABLE customer_addresses (
    address_id           NUMBER(10) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id          NUMBER(10) NOT NULL CONSTRAINT fk_addr_cust REFERENCES customers(customer_id),
    address_line1        VARCHAR2(200) NOT NULL,
    address_line2        VARCHAR2(200),
    city                 VARCHAR2(100) NOT NULL,
    state                VARCHAR2(50) NOT NULL,
    zip_code             VARCHAR2(20) NOT NULL,
    country              VARCHAR2(50) DEFAULT 'USA',
    is_shipping_default  CHAR(1) DEFAULT 'N' CONSTRAINT chk_addr_ship CHECK (is_shipping_default IN ('Y', 'N')),
    is_billing_default   CHAR(1) DEFAULT 'N' CONSTRAINT chk_addr_bill CHECK (is_billing_default IN ('Y', 'N'))
);

COMMENT ON TABLE customer_addresses IS '3NF: Moved address details out of ORDERS. City/State/Zip depend on Address_ID, not Order_ID.';

-- =============================================================================
-- 4. CATEGORY_MANAGERS (Explicitly built for BCNF demonstration)
--    Determinant: category_id determines manager_name. Thus, category_id is the key.
-- =============================================================================
CREATE TABLE category_managers (
    category_id    NUMBER(10) PRIMARY KEY CONSTRAINT fk_catmgr_cat REFERENCES categories(category_id),
    manager_name   VARCHAR2(100) NOT NULL,
    approval_level NUMBER(2) DEFAULT 1 CONSTRAINT chk_mgr_level CHECK (approval_level BETWEEN 1 AND 5)
);

COMMENT ON TABLE category_managers IS 'BCNF: Solves the issue where Category determines Manager. Manager is not a key for PROMOTIONS, so we split it out.';

-- =============================================================================
-- 5. PRODUCTS (2NF & 3NF Implementation)
--    Product details depend solely on product_id, NOT on order_id.
-- =============================================================================
CREATE TABLE products (
    product_id     NUMBER(10) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_id    NUMBER(10) NOT NULL CONSTRAINT fk_prod_cat REFERENCES categories(category_id),
    product_name   VARCHAR2(200) NOT NULL,
    current_price  NUMBER(10, 2) NOT NULL CONSTRAINT chk_prod_price CHECK (current_price >= 0),
    description    CLOB,
    sku            VARCHAR2(50) NOT NULL UNIQUE,
    weight_kg      NUMBER(5, 2) DEFAULT 0
);

COMMENT ON TABLE products IS '2NF: Removed Product_Name and Price from ORDER_ITEMS because they depend only on Product_ID, not the composite key (Order_ID + Product_ID).';
COMMENT ON COLUMN products.sku IS 'Unique SKU ensures no duplicate product entries.';

-- =============================================================================
-- 6. PRODUCT_INVENTORY (Core table for ACID Isolation - SELECT FOR UPDATE)
-- =============================================================================
CREATE TABLE product_inventory (
    product_id           NUMBER(10) PRIMARY KEY CONSTRAINT fk_inv_prod REFERENCES products(product_id),
    quantity_on_hand     NUMBER(10) DEFAULT 0 NOT NULL,
    reserved_qty         NUMBER(10) DEFAULT 0 NOT NULL,
    low_stock_threshold  NUMBER(10) DEFAULT 5,
    last_updated         TIMESTAMP DEFAULT SYSTIMESTAMP
);

COMMENT ON TABLE product_inventory IS 'ACID: We use SELECT...FOR UPDATE on this table to handle isolation and prevent overselling.';

-- =============================================================================
-- 7. PROMOTIONS (BCNF Implementation)
--    We removed MANAGER_NAME. Now Promotions purely handles Discount logic.
--    Category_ID is just an FK, and the actual manager is in CATEGORY_MANAGERS.
-- =============================================================================
CREATE TABLE promotions (
    promo_id         NUMBER(10) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_id      NUMBER(10) CONSTRAINT fk_promo_cat REFERENCES categories(category_id),
    promo_code       VARCHAR2(30) NOT NULL UNIQUE,
    discount_percent NUMBER(3) NOT NULL CONSTRAINT chk_promo_disc CHECK (discount_percent BETWEEN 0 AND 100),
    valid_from       DATE NOT NULL,
    valid_to         DATE NOT NULL,
    usage_limit      NUMBER(5),
    CONSTRAINT chk_promo_dates CHECK (valid_to >= valid_from)
);

COMMENT ON TABLE promotions IS 'BCNF: Manager_Name is removed because it is determined by Category_ID, not Promo_ID. That dependency is now properly housed in CATEGORY_MANAGERS.';

-- =============================================================================
-- 8. SHOPPING_CART
-- =============================================================================
CREATE TABLE shopping_cart (
    cart_id           NUMBER(10) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id       NUMBER(10) NOT NULL CONSTRAINT fk_cart_cust REFERENCES customers(customer_id),
    created_date      DATE DEFAULT SYSDATE,
    last_modified_date DATE DEFAULT SYSDATE,
    is_active         CHAR(1) DEFAULT 'Y' CONSTRAINT chk_cart_active CHECK (is_active IN ('Y', 'N'))
);

-- =============================================================================
-- 9. CART_ITEMS (1NF Demonstration)
--    No comma-separated lists. Each product gets a distinct row.
-- =============================================================================
CREATE TABLE cart_items (
    cart_item_id   NUMBER(10) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cart_id        NUMBER(10) NOT NULL CONSTRAINT fk_cartitem_cart REFERENCES shopping_cart(cart_id),
    product_id     NUMBER(10) NOT NULL CONSTRAINT fk_cartitem_prod REFERENCES products(product_id),
    quantity       NUMBER(5) NOT NULL CONSTRAINT chk_cart_qty CHECK (quantity > 0),
    added_date     DATE DEFAULT SYSDATE,
    CONSTRAINT uk_cart_item UNIQUE (cart_id, product_id) -- Prevents duplicate items in same cart
);

COMMENT ON TABLE cart_items IS '1NF: Products are not stored as a comma-separated string. Each product gets its own atomic row.';

-- =============================================================================
-- 10. ORDERS (3NF & ACID Center)
--     Notice: No Customer_Name, No City, No State. All transitive dependencies removed.
-- =============================================================================
CREATE TABLE orders (
    order_id            NUMBER(10) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id         NUMBER(10) NOT NULL CONSTRAINT fk_ord_cust REFERENCES customers(customer_id),
    shipping_address_id NUMBER(10) NOT NULL CONSTRAINT fk_ord_addr REFERENCES customer_addresses(address_id),
    promo_code          VARCHAR2(30) CONSTRAINT fk_ord_promo REFERENCES promotions(promo_code),
    order_date          DATE DEFAULT SYSDATE,
    total_amount        NUMBER(10, 2) DEFAULT 0 CONSTRAINT chk_ord_total CHECK (total_amount >= 0),
    status              VARCHAR2(20) DEFAULT 'PENDING' 
                        CONSTRAINT chk_ord_status CHECK (status IN ('PENDING', 'PAID', 'SHIPPED', 'DELIVERED', 'CANCELLED', 'PAYMENT_FAILED'))
);

COMMENT ON TABLE orders IS '3NF: Customer_Name, Email, City, State, Zip are NOT here. They belong to CUSTOMERS and ADDRESSES to avoid transitive dependency on Order_ID.';

-- =============================================================================
-- 11. ORDER_ITEMS (2NF Demonstration)
--     Composite PK: (Order_ID, Product_ID). We DO NOT store Product_Name or
--     Current_Price here because they depend ONLY on Product_ID (partial dependency).
-- =============================================================================
CREATE TABLE order_items (
    order_id        NUMBER(10) NOT NULL CONSTRAINT fk_orditem_ord REFERENCES orders(order_id),
    product_id      NUMBER(10) NOT NULL CONSTRAINT fk_orditem_prod REFERENCES products(product_id),
    quantity        NUMBER(5) NOT NULL CONSTRAINT chk_orditem_qty CHECK (quantity > 0),
    snapshot_price  NUMBER(10, 2) NOT NULL CONSTRAINT chk_orditem_price CHECK (snapshot_price >= 0), -- Historical price at order time
    CONSTRAINT pk_order_items PRIMARY KEY (order_id, product_id)
);

COMMENT ON TABLE order_items IS '2NF: Composite PK is (Order_ID, Product_ID). We removed Product_Name and Current_Price because they depend solely on Product_ID (partial dependency). They stay in PRODUCTS.';

-- =============================================================================
-- 12. PAYMENTS (ACID: Atomicity check for payment gateway)
-- =============================================================================
CREATE TABLE payments (
    payment_id          NUMBER(10) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id            NUMBER(10) NOT NULL UNIQUE CONSTRAINT fk_pay_ord REFERENCES orders(order_id), -- UNIQUE ensures 1-to-1 relation
    amount              NUMBER(10, 2) NOT NULL CONSTRAINT chk_pay_amt CHECK (amount >= 0),
    payment_date        DATE DEFAULT SYSDATE,
    gateway_reference   VARCHAR2(100), -- Mock transaction ID from gateway
    status              VARCHAR2(20) DEFAULT 'PENDING' 
                        CONSTRAINT chk_pay_status CHECK (status IN ('SUCCESS', 'FAILED', 'PENDING'))
);

-- =============================================================================
-- 13. SHIPMENTS
-- =============================================================================
CREATE TABLE shipments (
    shipment_id     NUMBER(10) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id        NUMBER(10) NOT NULL UNIQUE CONSTRAINT fk_ship_ord REFERENCES orders(order_id),
    tracking_number VARCHAR2(100),
    carrier_name    VARCHAR2(50),
    shipped_date    DATE,
    delivered_date  DATE,
    status          VARCHAR2(20) DEFAULT 'IN_TRANSIT' 
                    CONSTRAINT chk_ship_status CHECK (status IN ('IN_TRANSIT', 'DELIVERED', 'RETURNED'))
);

-- =============================================================================
-- 14. RETURNS
-- =============================================================================
CREATE TABLE returns (
    return_id       NUMBER(10) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id        NUMBER(10) NOT NULL CONSTRAINT fk_ret_ord REFERENCES orders(order_id),
    payment_id      NUMBER(10) NOT NULL CONSTRAINT fk_ret_pay REFERENCES payments(payment_id),
    return_date     DATE DEFAULT SYSDATE,
    reason          VARCHAR2(255),
    return_status   VARCHAR2(20) DEFAULT 'PENDING' 
                    CONSTRAINT chk_ret_status CHECK (return_status IN ('PENDING', 'APPROVED', 'REJECTED')),
    refund_amount   NUMBER(10, 2) CONSTRAINT chk_ret_refund CHECK (refund_amount >= 0),
    restock_status  CHAR(1) DEFAULT 'N' CONSTRAINT chk_ret_restock CHECK (restock_status IN ('Y', 'N'))
);

-- =============================================================================
-- 15. AUDIT_LOGS (ACID: Compliance & auditing)
--     Captures who changed what, for transaction traceability.
-- =============================================================================
CREATE TABLE audit_logs (
    log_id            NUMBER(15) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    table_name        VARCHAR2(30) NOT NULL,
    action            VARCHAR2(10) NOT NULL CONSTRAINT chk_audit_action CHECK (action IN ('INSERT', 'UPDATE', 'DELETE')),
    column_name       VARCHAR2(30),
    old_value         VARCHAR2(4000),
    new_value         VARCHAR2(4000),
    changed_by_user   VARCHAR2(100) DEFAULT USER, -- Captures Oracle session user
    change_timestamp  TIMESTAMP DEFAULT SYSTIMESTAMP
);

COMMENT ON TABLE audit_logs IS 'ACID & Compliance: Automatically populated by triggers to ensure full traceability of all changes.';


CREATE TABLE low_stock_alerts (
    alert_id        NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id      NUMBER NOT NULL,
    product_name    VARCHAR2(200),
    sku             VARCHAR2(50),
    current_stock   NUMBER,
    threshold       NUMBER,
    created_at      TIMESTAMP DEFAULT SYSTIMESTAMP,
    resolved_flag   CHAR(1) DEFAULT 'N' CONSTRAINT chk_resolved_flag CHECK (resolved_flag IN ('Y', 'N')),
    resolved_at     TIMESTAMP,
    comments        VARCHAR2(500)
);

COMMENT ON TABLE low_stock_alerts IS 'Persistent log of all low-stock conditions triggered by TRG_STOCK_ALERT.';
-- =============================================================================
-- VERIFICATION QUERY: Run this to see all tables and their structures.
-- =========================================================================
SELECT table_name, status FROM user_tables ORDER BY table_name;

